apiVersion: v1
kind: Pod
metadata:
  name: devicequery
spec:
  containers:
    - name: gpu-test
      image: jitteam/devicequery:latest
      command: [ "./deviceQuery" ]
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: PU
                operator: In
                values:
                - gpu
              - key: GPU-TYPE
                operator: In
                values:
                - nvidia
